name: 测试地图生成与部署

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy pyecharts
          pip list
      
      - name: 创建测试目录
        run: |
          mkdir -p test_deploy/maps
      
      - name: 测试地图生成
        run: |
          # 运行地图生成
          python static_map_generator.py -f data/sample_pollen_data.csv -o test_deploy
          
          # 列出生成的文件
          echo "生成的文件:"
          ls -la test_deploy/
          
          echo "地图文件夹内容:"
          ls -la test_deploy/maps/
          
          # 检查文件内容
          echo "检查index.html内容:"
          grep -n "maps/map_" test_deploy/index.html || echo "未找到地图引用"
          
          # 检查地图文件内容
          MAP_FILE=$(ls test_deploy/maps/ | head -n 1)
          echo "检查地图文件 $MAP_FILE 内容:"
          grep -n "echarts.min.js" test_deploy/maps/$MAP_FILE || echo "未找到echarts引用"
          grep -n "china.js" test_deploy/maps/$MAP_FILE || echo "未找到地图数据引用"
      
      - name: 测试部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: test_deploy
          branch: test-gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 部署结果
        run: |
          echo "部署测试完成!"
          echo "请检查 test-gh-pages 分支中的文件是否完整" 