name: 自动更新花粉数据

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00 (北京时间8:00)运行
  workflow_dispatch:    # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests
          
      - name: 设置Git用户
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: 更新花粉数据
        run: |
          python scripts/update_pollen_data.py --push
          
      # 注意：推送动作已在脚本中处理 