name: 自动更新花粉数据

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00 (北京时间8:00)运行
  workflow_dispatch:    # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests
          
      - name: 设置Git用户
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: 更新花粉数据
        run: |
          python scripts/update_pollen_data.py --push
          
      # 触发部署工作流
      - name: 等待更新数据提交
        run: |
          echo "等待10秒，确保数据更新提交已完成..."
          sleep 10
          
      - name: 手动触发部署工作流
        run: |
          # 使用GitHub API触发部署工作流
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-pollen-map.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}' \
            || echo "注意：无法自动触发部署工作流，但数据已更新" 